// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: 07_grpc_error/proto/err.proto

package grpcErrProtobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// @plugins=protoc-gen-go-errors
// 错误
type Error int32

const (
	// 未知类型
	// @code=UNKNOWN
	Error_RESOURCE_ERR_UNKNOWN Error = 0
	// 找不到资源
	// @code=NOT_FOUND
	Error_RESOURCE_ERR_NOT_FOUND Error = 101
	// 获取列表数据出错
	// @code=INTERNAL
	Error_RESOURCE_ERR_LIST_MYSQL Error = 102
	// 获取详情数据出错
	// @code=INTERNAL
	Error_RESOURCE_ERR_INFO_MYSQL Error = 103
)

// Enum value maps for Error.
var (
	Error_name = map[int32]string{
		0:   "RESOURCE_ERR_UNKNOWN",
		101: "RESOURCE_ERR_NOT_FOUND",
		102: "RESOURCE_ERR_LIST_MYSQL",
		103: "RESOURCE_ERR_INFO_MYSQL",
	}
	Error_value = map[string]int32{
		"RESOURCE_ERR_UNKNOWN":    0,
		"RESOURCE_ERR_NOT_FOUND":  101,
		"RESOURCE_ERR_LIST_MYSQL": 102,
		"RESOURCE_ERR_INFO_MYSQL": 103,
	}
)

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}

func (x Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error) Descriptor() protoreflect.EnumDescriptor {
	return file__07_grpc_error_proto_err_proto_enumTypes[0].Descriptor()
}

func (Error) Type() protoreflect.EnumType {
	return &file__07_grpc_error_proto_err_proto_enumTypes[0]
}

func (x Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error.Descriptor instead.
func (Error) EnumDescriptor() ([]byte, []int) {
	return file__07_grpc_error_proto_err_proto_rawDescGZIP(), []int{0}
}

var file__07_grpc_error_proto_err_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         1108,
		Name:          "default_code",
		Tag:           "varint,1108,opt,name=default_code",
		Filename:      "07_grpc_error/proto/err.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         1109,
		Name:          "code",
		Tag:           "varint,1109,opt,name=code",
		Filename:      "07_grpc_error/proto/err.proto",
	},
}

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional int32 default_code = 1108;
	E_DefaultCode = &file__07_grpc_error_proto_err_proto_extTypes[0]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional int32 code = 1109;
	E_Code = &file__07_grpc_error_proto_err_proto_extTypes[1]
)

var File__07_grpc_error_proto_err_proto protoreflect.FileDescriptor

var file__07_grpc_error_proto_err_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x30, 0x37, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x72, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2a, 0x77, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x45,
	0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45,
	0x5f, 0x45, 0x52, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x65,
	0x12, 0x1b, 0x0a, 0x17, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x45, 0x52, 0x52,
	0x5f, 0x4c, 0x49, 0x53, 0x54, 0x5f, 0x4d, 0x59, 0x53, 0x51, 0x4c, 0x10, 0x66, 0x12, 0x1b, 0x0a,
	0x17, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x5f, 0x49, 0x4e,
	0x46, 0x4f, 0x5f, 0x4d, 0x59, 0x53, 0x51, 0x4c, 0x10, 0x67, 0x3a, 0x40, 0x0a, 0x0c, 0x64, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6e, 0x75,
	0x6d, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd4, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x3a, 0x36, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x21, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xd5, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x42, 0x25, 0x5a, 0x23, 0x30, 0x37, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x67, 0x72, 0x70, 0x63,
	0x45, 0x72, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file__07_grpc_error_proto_err_proto_rawDescOnce sync.Once
	file__07_grpc_error_proto_err_proto_rawDescData = file__07_grpc_error_proto_err_proto_rawDesc
)

func file__07_grpc_error_proto_err_proto_rawDescGZIP() []byte {
	file__07_grpc_error_proto_err_proto_rawDescOnce.Do(func() {
		file__07_grpc_error_proto_err_proto_rawDescData = protoimpl.X.CompressGZIP(file__07_grpc_error_proto_err_proto_rawDescData)
	})
	return file__07_grpc_error_proto_err_proto_rawDescData
}

var file__07_grpc_error_proto_err_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file__07_grpc_error_proto_err_proto_goTypes = []interface{}{
	(Error)(0),                            // 0: Error
	(*descriptorpb.EnumOptions)(nil),      // 1: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 2: google.protobuf.EnumValueOptions
}
var file__07_grpc_error_proto_err_proto_depIdxs = []int32{
	1, // 0: default_code:extendee -> google.protobuf.EnumOptions
	2, // 1: code:extendee -> google.protobuf.EnumValueOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file__07_grpc_error_proto_err_proto_init() }
func file__07_grpc_error_proto_err_proto_init() {
	if File__07_grpc_error_proto_err_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file__07_grpc_error_proto_err_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file__07_grpc_error_proto_err_proto_goTypes,
		DependencyIndexes: file__07_grpc_error_proto_err_proto_depIdxs,
		EnumInfos:         file__07_grpc_error_proto_err_proto_enumTypes,
		ExtensionInfos:    file__07_grpc_error_proto_err_proto_extTypes,
	}.Build()
	File__07_grpc_error_proto_err_proto = out.File
	file__07_grpc_error_proto_err_proto_rawDesc = nil
	file__07_grpc_error_proto_err_proto_goTypes = nil
	file__07_grpc_error_proto_err_proto_depIdxs = nil
}
