// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire

import (
	"fmt"
)

// Injectors from wire.go:

// 声明injector注入器
func InitializeEvent() Event {
	message := NewMessage()
	greeter := NewGreeter(message)
	event := NewEvent(greeter)
	return event
}

// wire.go:

type Message string

type Greeter struct {
	Message Message // <- adding a Message field
}

// 宴会
type Event struct {
	Greeter Greeter // <- adding a Greeter field
}

//创建消息
func NewMessage() Message {
	return Message("Hi there!")
}

// 创建招待人
func NewGreeter(m Message) Greeter {
	return Greeter{Message: m}
}

// 绑定欢迎
func (g Greeter) Greet() Message {
	return g.Message
}

// 创建一场宴会
func NewEvent(g Greeter) Event {
	return Event{Greeter: g}
}

// 宴会开始
func (e Event) Start() {
	msg := e.Greeter.Greet()
	fmt.Println(msg)
}
