// Code generated by protoc-gen-go. DO NOT EDIT.
// source: 16_import_proto/dir_import/computer.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Computer struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cpu                  *CPU     `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory               *Memory  `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Computer) Reset()         { *m = Computer{} }
func (m *Computer) String() string { return proto.CompactTextString(m) }
func (*Computer) ProtoMessage()    {}
func (*Computer) Descriptor() ([]byte, []int) {
	return fileDescriptor_24756619f0787e27, []int{0}
}

func (m *Computer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Computer.Unmarshal(m, b)
}
func (m *Computer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Computer.Marshal(b, m, deterministic)
}
func (m *Computer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Computer.Merge(m, src)
}
func (m *Computer) XXX_Size() int {
	return xxx_messageInfo_Computer.Size(m)
}
func (m *Computer) XXX_DiscardUnknown() {
	xxx_messageInfo_Computer.DiscardUnknown(m)
}

var xxx_messageInfo_Computer proto.InternalMessageInfo

func (m *Computer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Computer) GetCpu() *CPU {
	if m != nil {
		return m.Cpu
	}
	return nil
}

func (m *Computer) GetMemory() *Memory {
	if m != nil {
		return m.Memory
	}
	return nil
}

func init() {
	proto.RegisterType((*Computer)(nil), "import.Computer")
}

func init() {
	proto.RegisterFile("16_import_proto/dir_import/computer.proto", fileDescriptor_24756619f0787e27)
}

var fileDescriptor_24756619f0787e27 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x34, 0x34, 0x8b, 0xcf,
	0xcc, 0x2d, 0xc8, 0x2f, 0x2a, 0x89, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0xc9, 0x2c, 0x82,
	0x0a, 0xe8, 0x27, 0xe7, 0xe7, 0x16, 0x94, 0x96, 0xa4, 0x16, 0xe9, 0x81, 0x65, 0x84, 0xd8, 0x20,
	0xc2, 0x52, 0x5a, 0x04, 0xb4, 0xe4, 0xe7, 0xa5, 0xe6, 0x95, 0x40, 0xf4, 0x28, 0xa5, 0x72, 0x71,
	0x38, 0x43, 0x4d, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x64, 0xb9, 0x98, 0x93, 0x0b, 0x4a, 0x25, 0x98, 0x14, 0x18, 0x35,
	0xb8, 0x8d, 0xb8, 0xf5, 0x20, 0xa6, 0xe8, 0x39, 0x07, 0x84, 0x06, 0x81, 0xc4, 0x85, 0xd4, 0xb8,
	0xd8, 0x72, 0x53, 0x73, 0xf3, 0x8b, 0x2a, 0x25, 0x98, 0xc1, 0x2a, 0xf8, 0x60, 0x2a, 0x7c, 0xc1,
	0xa2, 0x41, 0x50, 0x59, 0x27, 0xa5, 0x28, 0x05, 0xdc, 0x8e, 0xb2, 0x06, 0x0b, 0x24, 0xb1, 0x81,
	0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x3b, 0xa8, 0x25, 0xf2, 0x00, 0x00, 0x00,
}
